@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name swagger
GET {{host}}/doc/json HTTP/1.1
Content-Type: {{contentType}}

###

# @name getRoute
GET {{host}}/ HTTP/1.1
Content-Type: {{contentType}}

###

# @name getUsers
GET {{host}}/users HTTP/1.1
Content-Type: {{contentType}}

###

@userId = {{postUser.response.body.id}}

# @name getUserById
GET {{host}}/users/{{userId}} HTTP/1.1
Content-Type: {{contentType}}

###

# @name postUser
POST {{host}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "User",
  "login": "User",
  "password": "123"
}