@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name swagger
GET {{host}}/doc/json HTTP/1.1
Content-Type: {{contentType}}

###

# @name getRoute
GET {{host}}/ HTTP/1.1
Content-Type: {{contentType}}


