FROM node:16.13-alpine3.15 AS deps
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm install

FROM node:16.13-alpine3.15 AS runner
WORKDIR /app

COPY ./build .

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json

CMD [ "npm", "run", "start" ]

#no such file or directory, open '/app/package.json'