version: '3.7'

networks:
  ivp-rss-network:
    driver: bridge

services:
  ivp-rss-http-api:
    container_name: ivp-rss-http-api
    build:
      context: ./../
      dockerfile: ./docker/api/Dockerfile
    volumes:
      ['../src:/app/src', '../plugins:/app/plugins', '../types:/app/types', ../logs/:/app/logs]
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - ivp-rss-postgres-web
    networks:
      - ivp-rss-network
    env_file:
      ['../.env.docker']
  
  ivp-rss-postgres-web:
    container_name: ivp-rss-postgres-web
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:delegated
    networks:
      - ivp-rss-network
    env_file:
      ['../.env.orm']