version: '3.7'

networks:
  ivp-rss-network:
    driver: bridge

services:
  ivp-rss-http-api:
    container_name: ivp-rss-http-api
    build:
      context: ./../
      dockerfile: ./docker/api/Dockerfile
    volumes:
      [
        '../src:/app/src',
        '../logs:/app/logs',
        '../types:/app/types',
        '../plugins:/app/plugins',
        '../database:/app/database',
        './api/stored_files:/app/stored_files',
      ]
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - ivp-rss-postgres-web
    networks:
      - ivp-rss-network
    env_file: ['../.env']

  ivp-rss-postgres-web:
    container_name: ivp-rss-postgres-web
    build:
      context: ./../
      dockerfile: ./docker/postgres/Dockerfile
    restart: unless-stopped
    expose:
      - ${TYPEORM_PORT} # Publishes port to other containers but NOT to host machine
    environment:
      - POSTGRES_PORT=${TYPEORM_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:delegated
    networks:
      - ivp-rss-network
    env_file: [ '../.env' ]
    command: -p ${TYPEORM_PORT}
